version: '3'

services:
  postgres:
    container_name: postgres
    restart: always
    image: postgres:10
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=balticlsc
    volumes:
      - 'flask-app-db:/var/lib/postgresql/data'
    ports:
      - '5434:5432'

  backend-pop:
    container_name: backend-pop
    build:
      context: ./Pop-Grupa-A-Backend
      dockerfile: Dockerfile
    volumes:
      - './Pop-Grupa-A-Backend:/app'
    ports:
      - '5000:5000'
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: ./app/manage.py
      DATABASE_URL: 'postgresql://admin:123456@postgres:5432/balticlsc'
    depends_on:
      - postgres

  front-pop:
    container_name: front-pop
    build: ./Pop-Grupa-A-Frontend
    volumes:
      - './Pop-Grupa-A-Frontend:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true

volumes:
  flask-app-db: