"""foreign keys

Revision ID: 06557d7a0fa8
Revises: 1a019f1b9589
Create Date: 2019-11-05 20:18:47.709070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06557d7a0fa8'
down_revision = '1a019f1b9589'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ComputationAccount', 'password')
    op.create_foreign_key(None, 'ComputationTask', 'ComputationApplication', ['app_id'], ['id'])
    op.create_foreign_key(None, 'ComputationTask', 'ComputationAccount', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ComputationTask', type_='foreignkey')
    op.drop_constraint(None, 'ComputationTask', type_='foreignkey')
    op.add_column('ComputationAccount', sa.Column('password', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
