"""add_user_role

Revision ID: c018ef6a9c54
Revises: 8fa29ae8d4f1
Create Date: 2019-12-04 16:49:18.471583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c018ef6a9c54'
down_revision = '8fa29ae8d4f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    accountrole = sa.Enum('ADMIN', 'APP_USER', 'SUPPLIER', name='accountrole')
    accountrole.create(op.get_bind())
    op.add_column('ComputationAccount', sa.Column('role', sa.Enum('ADMIN', 'APP_USER', 'SUPPLIER', name='accountrole'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ComputationAccount', 'role')
    accountrole = sa.Enum('ADMIN', 'APP_USER', 'SUPPLIER', name='accountrole')
    accountrole.drop(op.get_bind())
    # ### end Alembic commands ###
