"""cluster_nodes_setup

Revision ID: c13c78ae550e
Revises: 06557d7a0fa8
Create Date: 2019-11-20 16:11:58.216452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c13c78ae550e'
down_revision = '06557d7a0fa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ClusterNodes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'SUBMITTED', 'ACTIVE', 'INACTIVE', 'DISABLED', name='nodestatus'), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Machines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cluster_node_id', sa.Integer(), nullable=False),
    sa.Column('cpus', sa.String(length=255), nullable=False),
    sa.Column('gpus', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['cluster_node_id'], ['ClusterNodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Machines')
    op.drop_table('ClusterNodes')
    # ### end Alembic commands ###
